#!/usr/bin/env python3
import sys
sys.dont_write_bytecode = True

from src.config import *
import sys
import os
from src.installer import installDeps

TEST_DIR = "src/test"



if __name__ == '__main__':
    if (len(sys.argv) < 3):
        raise Exception("Incorrect input")

    # installDeps()
    URL = sys.argv[1]
    path = sys.argv[2]
    gtoken = sys.argv[3]
    setToken(gtoken)
    # print(sys.argv)

    files = os.listdir(path)

    from src.run import newRun
    output = newRun(URL, path)
    print(f"{output[0]} {output[1]} {output[2]} {output[3]} {output[4]} {output[5]}")
    # for o in output:
        # print(o)
    # print(output)
# LOG_FILE.close()
